name: Test in docker container

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test app using pytest in container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
        docker compose run test
